### ISSUE TITLE
Version 0.9.3 does not compile

### ISSUE THREAD

**Issue by panwrona** [nuuneoi/FBLikeAndroid#1]
Hi, I've had an issue with version 0.9.3 in gradle. This one worked:

``` java
    compile 'com.inthecheesefactory.thecheeselibrary:fb-like:0.9.2'
```

**Comment by nuuneoi** [comment]
My apologies. I forgot to sync v0.9.3 to mavenCentral. I just did it minutes ago. Could you please try again and see whether it works or not now?

**Comment by panwrona** [comment]
Yeah, everything's just fine ;)
