### ISSUE TITLE
Error: android.view.InflateException

### ISSUE THREAD

**Issue by webschnecke** [nuuneoi/FBLikeAndroid#3]
I got this output:

Unable to start activity ComponentInfo{xxx.com.xxx/xxx.com.xxx.MainActivity}: android.view.InflateException: Binary XML file line #439: Error inflating class com.inthecheesefactory.lib.fblike.widget.FBLikeView

**Comment by nuuneoi** [comment]
May I have more details on stacktrace please?

By the way, please try to update the library to the latest version v1.0.0. It might helps.

**Comment by VAdaihiep** [comment]
@webschnecke Maybe I have same issue with you, Logcat show InflateException and ClassCastException. 

The reason is FBLikeView's id is "likeView", same with LikeView's id in FBLikeView.

So to fix it, just change FBLikeView's id to "fbLikeView" or somethings else.

**Comment by marcespinoza** [comment]
Same error :(

**Comment by webschnecke** [comment]
.

**Comment by VAdaihiep** [comment]
@marcespinoza 

> change FBLikeView's id to "fbLikeView"
